[project]
name = "fluree-py"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "James Sweet", email = "jsweet@nd.edu" }
]
requires-python = ">=3.10"
dependencies = [
    "httpx>=0.28.1",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
